apiVersion: batch/v1
kind: Job
metadata:
  name: on-demand-job
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - name: on-demand-job
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "echo $(date): On-demand job is running ...; sleep 5; echo Done.",
            ]
      restartPolicy: Never
